database:
  dsn: "postgres://voluntik_user:securepassword@pgbouncer:5432/voluntik?sslmode=disable"

redis:
  addr: "redis:6379"

server:
  port: "8080"
  environment: "development"
  post_login_redirect: "/"

google:
  client_id: ""
  client_secret: ""
  redirect_url: "http://localhost:8080/auth/google/callback"

jwt:
  secret: "your-super-secret-jwt-key"