name: voluntik_dev

services:
  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    image: voluntik-postgres
    container_name: voluntik-db-dev
    environment:
      POSTGRES_DB: voluntik
      POSTGRES_USER: voluntik_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth=md5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    build:
      context: .
      dockerfile: redis.Dockerfile
    image: voluntik-redis
    container_name: voluntik-redis-dev
    command: ["dragonfly", "--logtostderr"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: voluntik-pgbouncer-dev
    depends_on:
      - db
    ports:
      - "6432:5432"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=voluntik_user
      - DB_PASSWORD=securepassword
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=100
      - DEFAULT_POOL_SIZE=20

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend-dev.Dockerfile
    image: voluntik-backend-dev:latest
    container_name: voluntik-backend-dev
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - pgbouncer
      - redis
    volumes:
      - ../backend:/app
      - go-cache:/go
    environment:
      - DB_HOST=pgbouncer
      - DB_PORT=5432
      - REDIS_HOST=redis
      - CGO_ENABLED=0
    command: ["air", "-c", ".air.toml"]

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend-dev.Dockerfile
    image: voluntik-frontend
    container_name: voluntik-frontend-dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "true"
      NEXT_TELEMETRY_DISABLED: "1"
    command: ["/bin/sh", "-c", "if [ ! -d node_modules ]; then pnpm install; fi && pnpm dev --hostname 0.0.0.0 --port 3000"]
    volumes:
      - ../frontend:/app:cached
      - node_modules:/app/node_modules
      - next_build:/app/.next
      - pnpm_store:/root/.pnpm-store

volumes:
  db-data:
  redis-data:
  node_modules:
  next_build:
  pnpm_store:
  go-cache: